# baseURL = 'https://gray-coast-0d467ea10.5.azurestaticapps.net'
baseURL = 'https://georgeduta.com'
languageCode = 'en-us'
title = 'My Learning'
theme = "PaperMod"
ignoreErrors = ["error-remote-getjson"]

[params]
  favicon = "favicon.svg"
  ShowBreadCrumbs= "true"
  env= "production"
  footer = {
    trademark = "© 2024"
    author = "George"
    topText = ["Made with Hugo and GitHub", "hosted on Azure"]
    bottomText = ["Powered by Hugo"]
  }
