baseURL = 'https://white-bush-08e69b003.5.azurestaticapps.net/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "PaperMod"
ignoreErrors = ["error-remote-getjson"]

[params]
  favicon = "favicon.svg"
