baseURL = 'https://gray-coast-0d467ea10.5.azurestaticapps.net'
languageCode = 'en-us'
title = 'My Learning'
theme = "PaperMod"
ignoreErrors = ["error-remote-getjson"]

[params]
  favicon = "favicon.svg"
  ShowBreadCrumbs= "true"
  env= "production"
