# baseURL = 'https://gray-coast-0d467ea10.5.azurestaticapps.net'
baseURL = 'https://georgeduta.com'
languageCode = 'en-us'
title = 'My Learning'
theme = "PaperMod"
ignoreErrors = ["error-remote-getjson"]

[params]
  favicon = "favicon.svg"
  ShowBreadCrumbs= "true"
  env= "production"
  # Footer settings
  customFooter = "true"
  footerText = "© 2024 Your Website Name. All rights reserved."
  footerLinks = [
    { name = "Privacy Policy", url = "/privacy-policy/" },
    { name = "Terms of Service", url = "/terms-of-service/" },
    { name = "Contact", url = "/contact/" }
  ]
