# baseURL = 'https://gray-coast-0d467ea10.5.azurestaticapps.net' Azure
baseURL = 'https://georgeduta.com'
languageCode = 'en-us'
title = 'My Learning'
theme = "PaperMod"
ignoreErrors = ["error-remote-getjson"]

[params]
googleAnalytics = "G-2TXNCK65VC"
favicon = "favicon.svg"
ShowBreadCrumbs= "true"
env= "production"
enableRobotsTXT = true
ShowReadingTime = "true"
# ShowShareButtons = "true"
ShowPostNavLinks = "true"
ShowCodeCopyButtons= "true"
ShowArchiveCount = true 
    [params.archives]
    enabled = true
    path = "archives"
    posts = true
    annual = true
    monthly = true

    [params.cover]
    linkFullImages= "true"
    responsiveImages= "true"

    [params.homeInfoParams]
    Title = "Powerd by Github hosted in Azure"
    Content = "Created using Visual Studio Code with Github Copilot extension"

    [[params.socialIcons]]
    name = "github"
    url = "https://github.com/dutza"
    
    [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/geduta"

    [[params.socialIcons]]
    name = "microsoft"
    url = "https://azure.microsoft.com"


    [params.SEO]
    enabled = "true"


  
[[menu.main]]
identifier = "Categories"
name = "Categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "About"
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/posts/archives/"
weight = 30

