name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Clean up previous Hugo installation
        run: |
          sudo rm -rf /usr/local/bin/hugo
          
      - name: Install Hugo v0.136.5
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.136.5/hugo_0.136.5_Linux-64bit.tar.gz
          tar -xvzf hugo_0.136.5_Linux-64bit.tar.gz
          sudo mv hugo /usr/local/bin/
          hugo version
          
      - name: Set Hugo version for Oryx
        run: |
          echo "HUGO_VERSION=0.136.5" >> $GITHUB_ENV
          
      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_COAST_0D467EA10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "public" # Built app content directory - optional
          skip_build: "true"  # Allow Oryx to run the build process
          skip_api_build: "true"
          environment_variables: |
            OryxVersion=20240408.1  # Specify the Oryx version here
            HUGO_VERSION=0.137.0     # Ensure Oryx uses the correct Hugo version
          ###### End of Repository/Build Configurations ######
          
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_COAST_0D467EA10 }}
          action: "close"
